version: '3.1'
services:
  aidbox-ts-generator:
    image: "bedasoftware/aidbox-ts-generator:latest"
    command: ["-o", "/tmp/aidbox.ts", "-u", "http://devbox:8080", "--user", "$AIDBOX_CLIENT_ID", "--pass", "$AIDBOX_CLIENT_SECRET"]
    depends_on:
      devbox-healthcheck:
        condition: service_healthy
    links:
      - "devbox:devbox"
    env_file:
      - .env
    volumes:
      - ./aidbox.ts:/tmp/aidbox.ts
